{
  "abstract" : [
    {
      "text" : "A network error was encountered, encapsulating a ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation\/APIClientError",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " type describing the underlying error.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation",
        "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation\/OAuth2Error"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation\/OAuth2Error\/network(error:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:14AuthFoundation11OAuth2ErrorO7networkyAcA09APIClientD0O_tcACmF",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "case"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "network"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "externalParam",
        "text" : "error"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:14AuthFoundation14APIClientErrorO",
        "text" : "APIClientError"
      },
      {
        "kind" : "text",
        "text" : ")"
      }
    ],
    "modules" : [
      {
        "name" : "OktaIdx"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Case",
    "symbolKind" : "case",
    "title" : "OAuth2Error.network(error:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "macOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "case"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "network"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "error"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation\/APIClientError",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:14AuthFoundation14APIClientErrorO",
              "text" : "APIClientError"
            },
            {
              "kind" : "text",
              "text" : ")"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/authfoundation\/oauth2error\/network(error:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.okta.mobile.oktaidx/documentation/AuthFoundation": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "AuthFoundation",
  "type" : "topic",
  "url" : "\/documentation\/authfoundation"
},
"doc://com.okta.mobile.oktaidx/documentation/AuthFoundation/APIClientError": {
  "abstract" : [
    {
      "text" : "Errors that may occur at the API or network level.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "APIClientError"
    }
  ],
  "identifier" : "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation\/APIClientError",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "APIClientError"
    }
  ],
  "role" : "symbol",
  "title" : "APIClientError",
  "type" : "topic",
  "url" : "\/documentation\/authfoundation\/apiclienterror"
},
"doc://com.okta.mobile.oktaidx/documentation/AuthFoundation/OAuth2Error": {
  "abstract" : [
    {
      "text" : "Errors that may occur when interacting with OAuth2 endpoints.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "OAuth2Error"
    }
  ],
  "identifier" : "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation\/OAuth2Error",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "OAuth2Error"
    }
  ],
  "role" : "symbol",
  "title" : "OAuth2Error",
  "type" : "topic",
  "url" : "\/documentation\/authfoundation\/oauth2error"
},
"doc://com.okta.mobile.oktaidx/documentation/AuthFoundation/OAuth2Error/network(error:)": {
  "abstract" : [
    {
      "text" : "A network error was encountered, encapsulating a ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation\/APIClientError",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " type describing the underlying error.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "network"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "error"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:14AuthFoundation14APIClientErrorO",
      "text" : "APIClientError"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.okta.mobile.oktaidx\/documentation\/AuthFoundation\/OAuth2Error\/network(error:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "OAuth2Error.network(error:)",
  "type" : "topic",
  "url" : "\/documentation\/authfoundation\/oauth2error\/network(error:)"
}
}
}